[config]
default_to_workspace = true
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.default]
alias = "serve"

[tasks.cargo-fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-all]
script = '''
leptosfmt .
cargo fmt --all
cargo clippy --fix -- -D warnings
'''
[tasks.check-leptos]
command = "leptosfmt"
args = ["--check", "."]

[tasks.check-fmt]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.check-clippy]
command = "cargo"
args = ["check"]

[tasks.check]
dependencies = ["check-fmt", "check-leptos", "check-clippy"]

[tasks.leptos-fmt]
command = "leptosfmt"
args = ["."]

[tasks.format]
dependencies = ["cargo-fmt", "leptos-fmt"]

[tasks.fmt]
alias = "format"

[tasks.build]
command = "trunk"
args = ["build", "--no-default-features", "--release"]

[tasks.serve]
command = "trunk"
args = ["serve"]
